### ISSUE TITLE
add an option to spawn an instance

### ISSUE THREAD

**Issue by pbca26** [particle4dev/komodo-rpc-lib#20]
Title: [Persona name] should (not) be able to [overarching action]

Business/User Value: As [persona] I want to [action by user] so that [value or need met]

Acceptance Criteria
GIVEN [necessary context and preconditions for story]
WHEN [action]
THEN [reaction]

**DEV NOTES**
can you also add spawn? via function arg or something
https://github.com/KomodoPlatform/Agama/blob/master/routes/api/daemonControl.js#L238
it's good for debugging/dev when you need to restart an app multiple times running native

- https://dzone.com/articles/understanding-execfile-spawn-exec-and-fork-in-node

**DESIGN Notes**
None

---other items that you may add to a story---

**NEEDS PM**
None

**NEEDS DESIGN**
None

**Related issues**
https://github.com/particle4dev/komodo-rpc-lib/issues/13
https://github.com/particle4dev/komodo-rpc-lib/issues/22

/label ~"story"

**Comment by particle4dev** [comment]
@pbca26 In this articles, it said spawn is fit for the long-running application. I think it makes sense so I switch to use spawn by default.
Is there any case do you want to use execFile for running komodod?

- https://dzone.com/articles/understanding-execfile-spawn-exec-and-fork-in-node

- https://github.com/particle4dev/komodo-rpc-lib/blob/add-an-option-to-spawn-an-instance/src/daemon/control.js#L56

**Comment by pbca26** [comment]
okay, as long as you don't run it in detached mode

**Comment by particle4dev** [comment]
@pbca26 Hi just added detached option. Please double-check and let me know if it's good enough for your case.

example:
https://github.com/particle4dev/komodo-rpc-lib/blob/master/examples/start-chain-with-detacked-options.js

source:
https://github.com/particle4dev/komodo-rpc-lib/blob/master/src/daemon/control.js#L64
https://github.com/particle4dev/komodo-rpc-lib/blob/master/src/daemon/control.js#L73
