### ISSUE TITLE
add all KMD asset chains params

### ISSUE THREAD

**Issue by pbca26** [particle4dev/komodo-rpc-lib#26]
Title: [Persona name] should (not) be able to [overarching action]

Business/User Value: As [persona] I want to [action by user] so that [value or need met]

Acceptance Criteria
GIVEN [necessary context and preconditions for story]
WHEN [action]
THEN [reaction]

**DEV NOTES**

- https://github.com/KomodoPlatform/Agama/blob/dev/routes/chainParams.js

- How to use

https://github.com/KomodoPlatform/Agama/blob/dev/routes/api/addCoinShortcuts.js

**DESIGN Notes**
None

---other items that you may add to a story---

**NEEDS PM**
None

**NEEDS DESIGN**
None

**Related issues**
None

/label ~"story"

**Comment by particle4dev** [comment]
@pbca26 done
Please review this pull request

https://github.com/particle4dev/komodo-rpc-lib/pull/28/files

Demos are available here:

https://github.com/particle4dev/komodo-rpc-lib/tree/master/examples
